<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class OrganizationUnitsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        // If you don't want to truncate, remove these statements.
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('organization_units')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $now = Carbon::now()->toDateTimeString();

        $rows = [
            [
                'id' => 1,
                'name' => 'Majlis Bandaraya Shah Alam',
                'short_name' => 'MBSA',
                'parent_id' => null,
                'lft' => 1,
                'rgt' => 2,
                'depth' => 0,
                'district_id' => null,
                'address' => "Bahagian Tender Dan Ukur Bahan, \r\nTingkat 23, Wisma MBSA, \r\nPersiaran Perbandaran \r\n40000 Shah Alam Selangor",
                'latlng' => null,
                'tel' => '03-55105133',
                'fax' => null,
                'email' => '',
                'confirmation_agency' => 1,
                'user_id' => null,
                'type_id' => 3,
                'created_at' => '2005-12-29 01:44:10',
                'updated_at' => '2016-05-09 04:27:17',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 2,
                'name' => 'Majlis Perbandaran Sepang',
                'short_name' => 'MPSepang',
                'parent_id' => null,
                'lft' => 3,
                'rgt' => 4,
                'depth' => 0,
                'district_id' => null,
                'address' => "Persiaran Semarak Api\r\nCyberjaya\r\n63200 Sepang\r\nSelangor",
                'latlng' => null,
                'tel' => '03-83190200',
                'fax' => null,
                'email' => '',
                'confirmation_agency' => 1,
                'user_id' => null,
                'type_id' => 3,
                'created_at' => '2005-12-29 01:27:36',
                'updated_at' => '2015-06-07 11:59:42',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 3,
                'name' => 'Majlis Perbandaran Selayang',
                'short_name' => 'MPS',
                'parent_id' => null,
                'lft' => 5,
                'rgt' => 6,
                'depth' => 0,
                'district_id' => null,
                'address' => "Persiaran 3, Bandar Baru Selayang\r\n\r\n68100 Batu Caves\r\nSelangor",
                'latlng' => null,
                'tel' => '03-61204903',
                'fax' => null,
                'email' => '',
                'confirmation_agency' => 1,
                'user_id' => null,
                'type_id' => 3,
                'created_at' => '2005-12-29 01:52:24',
                'updated_at' => '2015-06-07 11:59:42',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 4,
                'name' => 'Majlis Perbandaran Kajang',
                'short_name' => 'MPKJ',
                'parent_id' => null,
                'lft' => 7,
                'rgt' => 8,
                'depth' => 0,
                'district_id' => null,
                'address' => "Jalan Semenyih\r\n\r\n43000 Kajang\r\nSelangor",
                'latlng' => null,
                'tel' => '03-87377899',
                'fax' => null,
                'email' => '',
                'confirmation_agency' => 1,
                'user_id' => null,
                'type_id' => 3,
                'created_at' => '2005-12-29 01:50:53',
                'updated_at' => '2015-06-07 11:59:42',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 5,
                'name' => 'Majlis Bandaraya Subang Jaya',
                'short_name' => 'MPSJ',
                'parent_id' => null,
                'lft' => 9,
                'rgt' => 10,
                'depth' => 0,
                'district_id' => null,
                'address' => "Persiaran Perpaduan, Jalan USJ5\r\n\r\n47610 Subang Jaya\r\nSelangor",
                'latlng' => null,
                'tel' => '03-80263131',
                'fax' => null,
                'email' => null,
                'confirmation_agency' => 1,
                'user_id' => null,
                'type_id' => 3,
                'created_at' => '2005-12-29 01:48:59',
                'updated_at' => '2020-10-20 07:10:34',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 6,
                'name' => 'Majlis Bandaraya Diraja Klang (MBDK)',
                'short_name' => 'MPK',
                'parent_id' => null,
                'lft' => 11,
                'rgt' => 12,
                'depth' => 0,
                'district_id' => null,
                'address' => "Jalan Perbandaran\r\n\r\n41675 Klang\r\nSelangor",
                'latlng' => null,
                'tel' => '03-33755555 smbg 3208',
                'fax' => null,
                'email' => null,
                'confirmation_agency' => 1,
                'user_id' => null,
                'type_id' => 3,
                'created_at' => '2005-12-29 01:47:31',
                'updated_at' => '2024-02-27 01:56:42',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 7,
                'name' => 'Majlis Bandaraya Petaling Jaya',
                'short_name' => 'MBPJ',
                'parent_id' => null,
                'lft' => 13,
                'rgt' => 14,
                'depth' => 0,
                'district_id' => null,
                'address' => "Jabatan Khidmat Pengurusan, Tingkat Bawah\r\nIbu Pejabat MBPJ, Jalan Yong Shook Lin\r\n46675 Petaling Jaya\r\nSelangor",
                'latlng' => null,
                'tel' => '03-79563544',
                'fax' => null,
                'email' => '',
                'confirmation_agency' => 1,
                'user_id' => null,
                'type_id' => 3,
                'created_at' => '2005-12-29 01:45:41',
                'updated_at' => '2015-06-07 11:59:42',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 13,
                'name' => 'Pejabat Daerah Petaling',
                'short_name' => 'Petaling',
                'parent_id' => null,
                'lft' => 15,
                'rgt' => 16,
                'depth' => 0,
                'district_id' => null,
                'address' => "No. 1, Persiaran Atmosfera,\r\nSeksyen U5,\r\n40150 Shah Alam\r\nSelangor",
                'latlng' => null,
                'tel' => '03-78419400',
                'fax' => null,
                'email' => '',
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 2,
                'created_at' => '2005-12-29 01:54:51',
                'updated_at' => '2015-06-07 11:59:42',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 14,
                'name' => 'Pejabat Daerah Klang',
                'short_name' => 'Klang',
                'parent_id' => null,
                'lft' => 17,
                'rgt' => 18,
                'depth' => 0,
                'district_id' => null,
                'address' => "Jalan Kota\r\n\r\n41902 Klang\r\nSelangor",
                'latlng' => null,
                'tel' => '03-33711963',
                'fax' => null,
                'email' => '',
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 2,
                'created_at' => '2005-12-29 01:56:31',
                'updated_at' => '2015-06-07 11:59:42',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 15,
                'name' => 'Pejabat Daerah Gombak',
                'short_name' => 'Gombak',
                'parent_id' => null,
                'lft' => 19,
                'rgt' => 20,
                'depth' => 0,
                'district_id' => null,
                'address' => "Bangunan Sultan Sulaiman\r\nKm. 16, Jalan Rawang\r\n68100 Batu Caves\r\nSelangor",
                'latlng' => null,
                'tel' => '03-61311020',
                'fax' => null,
                'email' => '',
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 2,
                'created_at' => '2005-12-29 01:57:59',
                'updated_at' => '2015-06-07 11:59:42',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 16,
                'name' => 'Pejabat Daerah Kuala Langat',
                'short_name' => 'Kuala Langat',
                'parent_id' => null,
                'lft' => 21,
                'rgt' => 22,
                'depth' => 0,
                'district_id' => null,
                'address' => "Telok Datok\r\n\r\n42700 Banting\r\nSelangor",
                'latlng' => null,
                'tel' => '03-31871225',
                'fax' => null,
                'email' => '',
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 2,
                'created_at' => '2005-12-29 01:59:30',
                'updated_at' => '2015-06-07 11:59:42',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 17,
                'name' => 'Pejabat Daerah Sepang',
                'short_name' => 'Sepang',
                'parent_id' => null,
                'lft' => 23,
                'rgt' => 24,
                'depth' => 0,
                'district_id' => null,
                'address' => "Bangunan Tun Aziz\r\nSalak Tinggi\r\n43900 Sepang\r\nSelangor",
                'latlng' => null,
                'tel' => '03-87061211',
                'fax' => null,
                'email' => '',
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 2,
                'created_at' => '2005-12-29 02:00:35',
                'updated_at' => '2015-06-07 11:59:42',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 18,
                'name' => 'Pejabat Daerah Sabak Bernam',
                'short_name' => 'Sabak Bernam',
                'parent_id' => null,
                'lft' => 25,
                'rgt' => 26,
                'depth' => 0,
                'district_id' => null,
                'address' => "Sabak Bernam\r\n\r\n45300 Sungai Besar\r\nSelangor",
                'latlng' => null,
                'tel' => '03-32241963',
                'fax' => null,
                'email' => '',
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 2,
                'created_at' => '2005-12-29 02:01:33',
                'updated_at' => '2015-06-07 11:59:42',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 19,
                'name' => 'Pejabat Daerah Hulu Langat',
                'short_name' => 'Hulu Langat',
                'parent_id' => null,
                'lft' => 27,
                'rgt' => 28,
                'depth' => 0,
                'district_id' => null,
                'address' => "Kompleks Pentadbiran Daerah\r\nBangunan Hishamuddin Alam Shah, Sek 9\r\n43650 Bandar Baru Bangi\r\nSelangor",
                'latlng' => null,
                'tel' => '03-89251992',
                'fax' => null,
                'email' => '',
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 2,
                'created_at' => '2005-12-29 02:02:55',
                'updated_at' => '2015-06-07 11:59:42',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 20,
                'name' => 'Pejabat Daerah Hulu Selangor',
                'short_name' => 'Hulu Selangor',
                'parent_id' => null,
                'lft' => 29,
                'rgt' => 30,
                'depth' => 0,
                'district_id' => null,
                'address' => "Jalan Bukit Kerajaan\r\n\r\n44000 Kuala Kubu Bharu\r\nSelangor",
                'latlng' => null,
                'tel' => '03-60641026',
                'fax' => null,
                'email' => '',
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 2,
                'created_at' => '2005-12-29 02:04:06',
                'updated_at' => '2015-06-07 11:59:42',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 21,
                'name' => 'Pejabat Daerah Kuala Selangor',
                'short_name' => 'Kuala Selangor',
                'parent_id' => null,
                'lft' => 31,
                'rgt' => 32,
                'depth' => 0,
                'district_id' => null,
                'address' => "Kuala Selangor\r\n\r\n45000 Kuala Selangor\r\nSelangor",
                'latlng' => null,
                'tel' => '03-32891010',
                'fax' => null,
                'email' => '',
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 2,
                'created_at' => '2005-12-29 02:05:05',
                'updated_at' => '2015-06-07 11:59:42',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 22,
                'name' => 'Pejabat SUK Selangor',
                'short_name' => 'SUK Sel',
                'parent_id' => null,
                'lft' => 33,
                'rgt' => 86,
                'depth' => 0,
                'district_id' => null,
                'address' => 'Bangunan SSAAS, 40503 Shah Alam, Selangor',
                'latlng' => null,
                'tel' => '03 - 55447000 ( Operator )',
                'fax' => null,
                'email' => 'tenderadmin@selangor.gov.my',
                'confirmation_agency' => 1,
                'user_id' => null,
                'type_id' => 1,
                'created_at' => '2005-12-29 02:07:31',
                'updated_at' => '2023-05-23 11:48:53',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 24,
                'name' => 'Jabatan Pengairan dan Saliran',
                'short_name' => 'JPS',
                'parent_id' => null,
                'lft' => 91,
                'rgt' => 112,
                'depth' => 0,
                'district_id' => null,
                'address' => "Tingkat 5, Podium Selatan, \r\nBangunan SSAAS, 40626, Shah Alam,\r\nSelangor Darul Ehsan\r\n\r\n40503 Shah Alam\r\nSelangor",
                'latlng' => null,
                'tel' => '03-55447791, 03-55447792 (Bahagian Ukur Bahan)',
                'fax' => null,
                'email' => null,
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 7,
                'created_at' => '2005-12-29 02:12:58',
                'updated_at' => '2023-05-23 11:48:53',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 25,
                'name' => 'Majlis Perbandaran Ampang Jaya',
                'short_name' => 'MPAJ',
                'parent_id' => null,
                'lft' => 113,
                'rgt' => 114,
                'depth' => 0,
                'district_id' => null,
                'address' => "Menara MPAJ, Persiaran MPAJ\r\nJalan Pandan Utama,\r\n55100 Pandan Indah\r\nKuala-Lumpur",
                'latlng' => null,
                'tel' => '03-42968000',
                'fax' => null,
                'email' => '',
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 3,
                'created_at' => '2005-12-29 01:24:05',
                'updated_at' => '2023-05-23 11:48:53',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 26,
                'name' => 'Majlis Perbandaran Kuala Langat',
                'short_name' => 'MDKL',
                'parent_id' => null,
                'lft' => 115,
                'rgt' => 116,
                'depth' => 0,
                'district_id' => null,
                'address' => "Bah. Teknologi Maklumat / Jab. Khidmat Pengurusan,\r\nPersiaran Majlis, Off Jalan Sultan Alam Shah\r\n42700 Banting\r\nSelangor",
                'latlng' => null,
                'tel' => '03-31872825',
                'fax' => null,
                'email' => null,
                'confirmation_agency' => 1,
                'user_id' => null,
                'type_id' => 3,
                'created_at' => '2005-12-29 01:31:07',
                'updated_at' => '2023-05-23 11:48:53',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 27,
                'name' => 'Majlis Perbandaran Hulu Selangor',
                'short_name' => 'MDHS',
                'parent_id' => null,
                'lft' => 117,
                'rgt' => 118,
                'depth' => 0,
                'district_id' => null,
                'address' => "Bah. Teknologi Maklumat, Jab. Khidmat Pengurusan,\r\nMPHS, Jalan Bukit Kerajaan, Kuala Kubu Bharu\r\n44000 Hulu Selangor\r\nSelangor",
                'latlng' => null,
                'tel' => '03-60641331',
                'fax' => null,
                'email' => null,
                'confirmation_agency' => 1,
                'user_id' => null,
                'type_id' => 3,
                'created_at' => '2005-12-29 01:33:14',
                'updated_at' => '2023-05-23 11:48:53',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 28,
                'name' => 'Majlis Perbandaran Kuala Selangor',
                'short_name' => 'MDKS',
                'parent_id' => null,
                'lft' => 119,
                'rgt' => 120,
                'depth' => 0,
                'district_id' => null,
                'address' => "Jalan Semarak\r\n\r\n45000 Kuala Selangor\r\nSelangor",
                'latlng' => null,
                'tel' => '03-32891439',
                'fax' => null,
                'email' => null,
                'confirmation_agency' => 1,
                'user_id' => null,
                'type_id' => 3,
                'created_at' => '2005-12-29 01:37:10',
                'updated_at' => '2023-05-23 11:48:53',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 29,
                'name' => 'Majlis Daerah Sabak Bernam',
                'short_name' => 'MDSB',
                'parent_id' => null,
                'lft' => 121,
                'rgt' => 122,
                'depth' => 0,
                'district_id' => null,
                'address' => "Jab. Pembangunan Dan Penyelenggaraan,\r\nBah. Pembangunan Projek, Sungai Besar\r\n45300 Sungai Besar\r\nSelangor",
                'latlng' => null,
                'tel' => '03-32241655',
                'fax' => null,
                'email' => '',
                'confirmation_agency' => 1,
                'user_id' => null,
                'type_id' => 3,
                'created_at' => '2005-12-29 01:41:51',
                'updated_at' => '2023-05-23 11:48:53',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 30,
                'name' => 'Jabatan Agama Islam Selangor',
                'short_name' => 'JAIS',
                'parent_id' => null,
                'lft' => 123,
                'rgt' => 124,
                'depth' => 0,
                'district_id' => null,
                'address' => "Bangunan Sultan Idris Shah\r\nPersiaran Masjid, Seksyen 5\r\n40000 Shah Alam\r\nSelangor",
                'latlng' => null,
                'tel' => '03-55143430',
                'fax' => null,
                'email' => null,
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 8,
                'created_at' => '2006-02-03 02:42:18',
                'updated_at' => '2023-05-23 11:48:53',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 31,
                'name' => 'Pejabat Tanah Dan Galian Selangor',
                'short_name' => 'PTGS',
                'parent_id' => null,
                'lft' => 87,
                'rgt' => 88,
                'depth' => 0,
                'district_id' => null,
                'address' => "Tingkat Bawah, Bangunan SSAAS\r\n\r\n40503 Shah Alam\r\nSelangor",
                'latlng' => null,
                'tel' => '03-55447575',
                'fax' => null,
                'email' => '',
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 4,
                'created_at' => '2006-02-03 02:47:00',
                'updated_at' => '2023-05-23 11:48:53',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 32,
                'name' => 'Jabatan Perancang Bandar & Desa',
                'short_name' => 'JPBD Selangor',
                'parent_id' => null,
                'lft' => 89,
                'rgt' => 90,
                'depth' => 0,
                'district_id' => null,
                'address' => "Tingkat 15-18\r\nBangunan Darul Ehsan\r\n40000 Shah Alam\r\nSelangor",
                'latlng' => null,
                'tel' => '03-55116666',
                'fax' => null,
                'email' => '',
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 4,
                'created_at' => '2006-02-16 06:48:51',
                'updated_at' => '2023-05-23 11:48:53',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 33,
                'name' => 'Perbendaharaan Negeri Selangor',
                'short_name' => 'PWN',
                'parent_id' => 22,
                'lft' => 34,
                'rgt' => 35,
                'depth' => 1,
                'district_id' => null,
                'address' => "Tingkat 12, Bangunan SSAAS\r\n\r\n40503 Shah Alam\r\nSelangor",
                'latlng' => null,
                'tel' => '03-55447000',
                'fax' => null,
                'email' => null,
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 5,
                'created_at' => '2006-02-16 06:58:37',
                'updated_at' => '2023-05-01 12:40:12',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 34,
                'name' => 'Perbadanan Adat Melayu Dan Warisan Negeri Selangor',
                'short_name' => 'PADAT',
                'parent_id' => null,
                'lft' => 125,
                'rgt' => 126,
                'depth' => 0,
                'district_id' => null,
                'address' => "Tingkat 1, Muzium Sultan Alam Shah\r\nPersiaran Perbandaran\r\n40000 Shah Alam\r\nSelangor",
                'latlng' => null,
                'tel' => '03-55190050',
                'fax' => null,
                'email' => '',
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 4,
                'created_at' => '2006-02-16 07:04:54',
                'updated_at' => '2023-05-23 11:48:53',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 35,
                'name' => 'Jabatan Perhutanan Selangor',
                'short_name' => 'Jabatan Hutan',
                'parent_id' => null,
                'lft' => 127,
                'rgt' => 128,
                'depth' => 0,
                'district_id' => null,
                'address' => "Tingkat 3, Bangunan SSAAS\r\n\r\n40503 Shah Alam\r\nSelangor",
                'latlng' => null,
                'tel' => '03-55447498',
                'fax' => null,
                'email' => null,
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 8,
                'created_at' => '2006-05-11 06:50:16',
                'updated_at' => '2023-05-23 11:48:53',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 36,
                'name' => 'Jabatan Kehakiman Syariah Selangor Darul Ehsan',
                'short_name' => 'JAKESS',
                'parent_id' => 22,
                'lft' => 84,
                'rgt' => 85,
                'depth' => 1,
                'district_id' => null,
                'address' => "Bangunan Mahkamah Syariah Sultan Idris Shah,\r\nPersiaran Masjid, Seksyen 5, \r\n40000 Shah Alam, Selangor Darul Ehsan.",
                'latlng' => null,
                'tel' => '03-55191291',
                'fax' => null,
                'email' => 'www.jakess.gov.my',
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 1,
                'created_at' => '2007-07-31 03:20:39',
                'updated_at' => '2023-05-23 11:48:53',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 37,
                'name' => 'Jabatan Pengairan dan Saliran Daerah Sepang',
                'short_name' => 'JPS SEPANG',
                'parent_id' => 24,
                'lft' => 94,
                'rgt' => 95,
                'depth' => 1,
                'district_id' => null,
                'address' => "Tingkat 2, Bangunan Tun Aziz,\r\nSalak Tinggi\r\n43900 Sepang\r\nSelangor Darul Ehsan",
                'latlng' => null,
                'tel' => '03-87063753',
                'fax' => null,
                'email' => null,
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 7,
                'created_at' => '2008-12-15 02:23:05',
                'updated_at' => '2023-05-23 11:48:53',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 38,
                'name' => 'Jabatan Pengairan dan Saliran Daerah Klang',
                'short_name' => 'JPS KLANG',
                'parent_id' => 24,
                'lft' => 96,
                'rgt' => 97,
                'depth' => 1,
                'district_id' => null,
                'address' => "Jalan Taliair\r\n41000 Klang\r\nSelangor Darul Ehsan",
                'latlng' => null,
                'tel' => '03-33712464',
                'fax' => null,
                'email' => null,
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 7,
                'created_at' => '2008-12-15 02:28:12',
                'updated_at' => '2023-05-23 11:48:53',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 39,
                'name' => 'Jabatan Pengairan dan Saliran Daerah Gombak',
                'short_name' => 'JPS GOMBAK',
                'parent_id' => 24,
                'lft' => 98,
                'rgt' => 99,
                'depth' => 1,
                'district_id' => null,
                'address' => "Tingkat 3, Bangunan Sultan Sulaiman\r\nKm 16, Jalan Ipoh\r\n68100 Batu Caves\r\nSelangor Darul Ehsan",
                'latlng' => null,
                'tel' => '03-61368342',
                'fax' => null,
                'email' => null,
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 7,
                'created_at' => '2008-12-15 02:31:13',
                'updated_at' => '2023-05-23 11:48:53',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 40,
                'name' => 'Jabatan Pengairan dan Saliran Daerah Sabak Bernam',
                'short_name' => 'JPS SABAK BERNAM',
                'parent_id' => 24,
                'lft' => 92,
                'rgt' => 93,
                'depth' => 1,
                'district_id' => null,
                'address' => "Komplek Pejabat Kerajaan Sabak Bernam\r\n\r\n45200 Sabak Bernam\r\nSelangor Darul Ehsan",
                'latlng' => null,
                'tel' => '03-32246670',
                'fax' => null,
                'email' => null,
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 7,
                'created_at' => '2008-12-15 02:35:31',
                'updated_at' => '2023-05-23 11:48:53',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 41,
                'name' => 'Jabatan Pengairan dan Saliran Daerah K. Selangor',
                'short_name' => 'JPS K SELANGOR',
                'parent_id' => 24,
                'lft' => 100,
                'rgt' => 101,
                'depth' => 1,
                'district_id' => null,
                'address' => "JPS Wilayah Kuala Selangor\r\n\r\n45000 Kuala Selangor\r\nSelangor Darul Ehsan",
                'latlng' => null,
                'tel' => '03-32897569',
                'fax' => null,
                'email' => null,
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 7,
                'created_at' => '2008-12-15 02:40:47',
                'updated_at' => '2023-05-23 11:48:53',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 42,
                'name' => 'Jabatan Pengairan dan Saliran Daerah Hulu Langat',
                'short_name' => 'JPS H LANGAT',
                'parent_id' => 24,
                'lft' => 102,
                'rgt' => 103,
                'depth' => 1,
                'district_id' => null,
                'address' => "Jln Persiaran Kemajuan, Seksyen 16, \r\n3650 Bandar Baru Bangi,\r\nSelangor Darul Ehsan",
                'latlng' => null,
                'tel' => '03-89252473 / 03-89209727 Faks : 03-89209728',
                'fax' => null,
                'email' => null,
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 7,
                'created_at' => '2008-12-15 02:50:27',
                'updated_at' => '2023-05-23 11:48:53',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 43,
                'name' => 'Jabatan Pengairan dan Saliran Daerah Kuala Langat',
                'short_name' => 'JPS K LANGAT',
                'parent_id' => 24,
                'lft' => 104,
                'rgt' => 105,
                'depth' => 1,
                'district_id' => null,
                'address' => "JPS Kuala Langat\r\n\r\n42700 Banting\r\nSelangor Darul Ehsan",
                'latlng' => null,
                'tel' => '03-31876561',
                'fax' => null,
                'email' => null,
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 7,
                'created_at' => '2008-12-15 02:52:32',
                'updated_at' => '2023-05-23 11:48:53',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 44,
                'name' => 'Jabatan Pengairan dan Saliran Daerah Hulu Selangor',
                'short_name' => 'JPS H SELANGOR',
                'parent_id' => 24,
                'lft' => 106,
                'rgt' => 107,
                'depth' => 1,
                'district_id' => null,
                'address' => "Tingkat 2, Bangunan Baru\r\nPejabat Daerah Hulu Selangor\r\n44000 Kuala Kubu Baru\r\nSelangor Darul Ehsan",
                'latlng' => null,
                'tel' => '03-60641342',
                'fax' => null,
                'email' => null,
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 7,
                'created_at' => '2008-12-15 03:01:31',
                'updated_at' => '2023-05-23 11:48:53',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 45,
                'name' => 'Jabatan Pengairan dan Saliran Petaling',
                'short_name' => 'JPS PETALING',
                'parent_id' => 24,
                'lft' => 108,
                'rgt' => 109,
                'depth' => 1,
                'district_id' => null,
                'address' => "Tingkat 4, Kompleks Pejabat Daerah Petaling,\r\nNo.1, Persiaran Atmosfera, Seksyen U5\r\n40150 Shah Alam\r\nSelangor",
                'latlng' => null,
                'tel' => '03-78460127',
                'fax' => null,
                'email' => null,
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 7,
                'created_at' => '2009-07-29 02:41:23',
                'updated_at' => '2023-05-23 11:48:53',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 46,
                'name' => 'JPS Bahagian Perkhidmatan Mekanikal',
                'short_name' => 'JPS BPM',
                'parent_id' => 24,
                'lft' => 110,
                'rgt' => 111,
                'depth' => 1,
                'district_id' => null,
                'address' => "Jalan Sepat 17/57,\r\nSeksyen 17,\r\n40000 Shah Alam\r\nSelangor",
                'latlng' => null,
                'tel' => '03-55199022',
                'fax' => null,
                'email' => null,
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 7,
                'created_at' => '2009-08-20 01:24:20',
                'updated_at' => '2023-05-23 11:48:53',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 47,
                'name' => 'Seksyen Sektoral, UPEN',
                'short_name' => 'UPEN Sektoral',
                'parent_id' => 22,
                'lft' => 36,
                'rgt' => 37,
                'depth' => 1,
                'district_id' => null,
                'address' => 'Tingkat 5, Bangunan SSAAS\r\n40503 Shah Alam, Selangor',
                'latlng' => null,
                'tel' => '0355447920',
                'fax' => null,
                'email' => '',
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 1,
                'created_at' => '2010-06-10 08:47:17',
                'updated_at' => '2019-04-16 04:56:54',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 48,
                'name' => 'Bahagian Pengurusan  Maklumat',
                'short_name' => 'BPM Selangor',
                'parent_id' => 22,
                'lft' => 44,
                'rgt' => 47,
                'depth' => 1,
                'district_id' => null,
                'address' => "Tingkat 2, Bahagian Pengurusan Maklumat,\r\nBangunan Sultan Salahuddin Abdul Aziz Shah\r\n40503 Shah Alam. Selangor Darul Ehsan",
                'latlng' => null,
                'tel' => '03 - 55447796',
                'fax' => null,
                'email' => 'tenderadmin@selangor.gov.my',
                'confirmation_agency' => 1,
                'user_id' => null,
                'type_id' => 1,
                'created_at' => '2011-03-02 04:12:58',
                'updated_at' => '2022-10-12 01:01:19',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 49,
                'name' => 'Jabatan Pertanian Selangor',
                'short_name' => 'JPNS',
                'parent_id' => 22,
                'lft' => 82,
                'rgt' => 83,
                'depth' => 1,
                'district_id' => null,
                'address' => "TINGKAT 4, BANGUNAN DARUL EHSAN\r\nNO 3 JALAN INDAH SEKSYEN 14\r\n40632 SHAH ALAM\r\nSELANGOR",
                'latlng' => null,
                'tel' => '03-5518 9888',
                'fax' => null,
                'email' => null,
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 1,
                'created_at' => '2011-03-22 06:57:49',
                'updated_at' => '2023-05-23 11:46:54',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 50,
                'name' => 'Jabatan Kerja Raya Negeri Selangor',
                'short_name' => 'JKR Selangor',
                'parent_id' => null,
                'lft' => 129,
                'rgt' => 148,
                'depth' => 0,
                'district_id' => null,
                'address' => "Kompleks Ibu Pejabat, Jabatan Kerja Raya Selangor, Persiaran Jubli Perak Seksyen 17, 40200  Shah Alam, Selangor",
                'latlng' => null,
                'tel' => '03-55455833',
                'fax' => null,
                'email' => null,
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 6,
                'created_at' => '2011-03-28 08:37:10',
                'updated_at' => '2023-05-23 11:34:18',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 51,
                'name' => 'Jabatan Kerja Raya Hulu Selangor',
                'short_name' => 'JKR Hulu Selangor',
                'parent_id' => 50,
                'lft' => 130,
                'rgt' => 131,
                'depth' => 1,
                'district_id' => null,
                'address' => "Jurutera Daerah, JKR Daerah Hulu Selangor\r\nKuala Kubu Baru\r\n44000 Kuala Kubu Baru\r\nSelangor",
                'latlng' => null,
                'tel' => '03-60642742',
                'fax' => null,
                'email' => null,
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 6,
                'created_at' => '2012-03-07 02:43:10',
                'updated_at' => '2023-05-23 11:34:49',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 52,
                'name' => 'Jabatan Kerja Raya Petaling',
                'short_name' => 'JKR Petaling',
                'parent_id' => 50,
                'lft' => 132,
                'rgt' => 133,
                'depth' => 1,
                'district_id' => null,
                'address' => "Tingkat 3, Pejabat Kerajaan Daerah Petaling,\r\nNo.1, Persiaran Atmosfera, Seksyen U5,\r\n40150 Shah Alam\r\nSelangor",
                'latlng' => null,
                'tel' => '03-78392400',
                'fax' => null,
                'email' => null,
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 6,
                'created_at' => '2012-03-09 02:58:08',
                'updated_at' => '2023-05-23 11:35:39',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 53,
                'name' => 'Jabatan Kerja Raya Gombak',
                'short_name' => 'JKR Gombak',
                'parent_id' => 50,
                'lft' => 134,
                'rgt' => 135,
                'depth' => 1,
                'district_id' => null,
                'address' => "Bangunan Sultan Sulaiman, Persiaran Pegawai\r\nBandar Baru Selayang\r\n68100 Batu Caves\r\nSelangor",
                'latlng' => null,
                'tel' => '03-61311311',
                'fax' => null,
                'email' => null,
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 6,
                'created_at' => '2012-03-16 04:15:21',
                'updated_at' => '2023-05-23 11:35:54',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 54,
                'name' => 'Jabatan Kerja Raya Sabak Bernam',
                'short_name' => 'JKR Sabak Bernam',
                'parent_id' => 50,
                'lft' => 136,
                'rgt' => 137,
                'depth' => 1,
                'district_id' => null,
                'address' => "Pejabat Jurutera Daerah, JKR Sabak Bernam\r\nSungai Besar, Selangor\r\n45300 Sungai Besar\r\nSelangor",
                'latlng' => null,
                'tel' => '03-32242581',
                'fax' => null,
                'email' => null,
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 6,
                'created_at' => '2012-03-22 08:18:19',
                'updated_at' => '2023-05-23 11:36:18',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 55,
                'name' => 'Jabatan Kerja Raya Hulu Langat',
                'short_name' => 'JKR Hulu Langat',
                'parent_id' => 50,
                'lft' => 138,
                'rgt' => 139,
                'depth' => 1,
                'district_id' => null,
                'address' => "Pejabat Jurutera Daerah, JKR Hulu Langat\r\nPersiaran Wawasan, Seksyen 14\r\n43650 Bandar Baru Bangi\r\nSelangor",
                'latlng' => null,
                'tel' => '03-89114040',
                'fax' => null,
                'email' => null,
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 6,
                'created_at' => '2012-03-26 07:13:56',
                'updated_at' => '2023-05-23 11:35:14',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 56,
                'name' => 'Jabatan Kerja Raya Kuala Selangor',
                'short_name' => 'JKR Kuala Selangor',
                'parent_id' => 50,
                'lft' => 140,
                'rgt' => 141,
                'depth' => 1,
                'district_id' => null,
                'address' => "Pejabat Jurutera Daerah\r\nJKR Kuala Selangor, Jalan Kemajuan\r\n45000 Kuala Selangor\r\nSelangor",
                'latlng' => null,
                'tel' => '03-32891040',
                'fax' => null,
                'email' => null,
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 6,
                'created_at' => '2012-03-28 04:00:51',
                'updated_at' => '2023-05-23 11:36:35',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 57,
                'name' => 'Jabatan Kerja Raya Klang',
                'short_name' => 'JKR Klang',
                'parent_id' => 50,
                'lft' => 142,
                'rgt' => 143,
                'depth' => 1,
                'district_id' => null,
                'address' => "No.1,Lorong Senbilang 8E\r\nOff Jalan Tepi Sungai\r\n41100 Klang\r\nSelangor",
                'latlng' => null,
                'tel' => '03-33714040',
                'fax' => null,
                'email' => null,
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 6,
                'created_at' => '2012-09-26 00:26:13',
                'updated_at' => '2023-05-23 11:36:50',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 58,
                'name' => 'Jabatan Kerja Raya Kuala Langat',
                'short_name' => 'JKR Kuala Langat',
                'parent_id' => 50,
                'lft' => 146,
                'rgt' => 147,
                'depth' => 1,
                'district_id' => null,
                'address' => "Telok Datok\r\n\r\n42700 Banting\r\nSelangor",
                'latlng' => null,
                'tel' => '03-31871025',
                'fax' => null,
                'email' => null,
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 6,
                'created_at' => '2012-09-26 00:31:18',
                'updated_at' => '2023-05-23 11:37:06',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 59,
                'name' => 'Jabatan Kerja Raya Sepang',
                'short_name' => 'JKR Sepang',
                'parent_id' => 50,
                'lft' => 144,
                'rgt' => 145,
                'depth' => 1,
                'district_id' => null,
                'address' => "Bangunan Tun Aziz\r\nSalak Tinggi\r\n43900 Sepang\r\nSelangor",
                'latlng' => null,
                'tel' => '03-87061040',
                'fax' => null,
                'email' => null,
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 6,
                'created_at' => '2012-09-26 00:33:47',
                'updated_at' => '2023-05-23 11:37:16',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 60,
                'name' => 'Seksyen Pihak Berkuasa Tempatan, UPEN',
                'short_name' => 'UPEN PBT',
                'parent_id' => 22,
                'lft' => 38,
                'rgt' => 39,
                'depth' => 1,
                'district_id' => null,
                'address' => "Tingkat 4, Bangunan Sultan Salahuddin Abdul Aziz Shah\r\n40000 Shah Alam, Selangor",
                'latlng' => null,
                'tel' => '03-55447100 / 03-55212326 / 03-55212381',
                'fax' => null,
                'email' => '',
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 1,
                'created_at' => '2012-09-26 01:10:28',
                'updated_at' => '2017-09-19 08:08:09',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 61,
                'name' => 'Lembaga Urus Air Selangor',
                'short_name' => 'LUAS',
                'parent_id' => null,
                'lft' => 149,
                'rgt' => 150,
                'depth' => 0,
                'district_id' => null,
                'address' => "Tingkat 12 & 13, Bangunan Darul Ehsan,\r\nNo.3, Jalan Indah, Seksyen 14,\r\n40000 Shah Alam\r\nSelangor",
                'latlng' => null,
                'tel' => '03-55111800',
                'fax' => null,
                'email' => '',
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 4,
                'created_at' => '2012-11-01 06:38:21',
                'updated_at' => '2023-05-23 11:29:43',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 62,
                'name' => 'Pusat Latihan Awam Selangor',
                'short_name' => 'PULAPES',
                'parent_id' => 22,
                'lft' => 54,
                'rgt' => 55,
                'depth' => 1,
                'district_id' => null,
                'address' => "Pusat Latihan Awam Selangor (PLAS)\r\nLot 7, Jalan Pantai Morib, 42700 Banting, Kuala Langat\r\nSelangor",
                'latlng' => null,
                'tel' => '03-31982146',
                'fax' => null,
                'email' => null,
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 1,
                'created_at' => '2012-11-23 00:13:09',
                'updated_at' => '2023-05-23 11:22:57',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 63,
                'name' => 'Jabatan Perkhidmatan Veterinar Negeri Selangor',
                'short_name' => 'DV Sel',
                'parent_id' => null,
                'lft' => 151,
                'rgt' => 152,
                'depth' => 0,
                'district_id' => null,
                'address' => "Lot 28,  Jalan Utas 15/7\r\nSeksyen 15\r\n40200 Shah Alam\r\nSelangor",
                'latlng' => null,
                'tel' => '03-55103900',
                'fax' => null,
                'email' => null,
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 4,
                'created_at' => '2013-02-08 07:04:44',
                'updated_at' => '2023-07-17 03:36:12',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 64,
                'name' => 'Perbadanan Kemajuan Negeri Selangor',
                'short_name' => 'PKNS',
                'parent_id' => null,
                'lft' => 153,
                'rgt' => 154,
                'depth' => 0,
                'district_id' => null,
                'address' => "Perbadanan Kemajuan Negeri Selangor,\r\nBangunan Ibu Pejabat PKNS,\r\nNo.2, Jalan Indah 14/8 Seksyen 14,\r\n40000 Shah Alam, Selangor Darul Ehsan.",
                'latlng' => null,
                'tel' => '03-55250300',
                'fax' => null,
                'email' => null,
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 4,
                'created_at' => '2013-02-14 03:07:51',
                'updated_at' => '2023-05-23 11:29:43',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 65,
                'name' => 'Majlis Agama Islam Selangor',
                'short_name' => 'MAIS',
                'parent_id' => null,
                'lft' => 155,
                'rgt' => 156,
                'depth' => 0,
                'district_id' => null,
                'address' => "Tgkt. 9 & 10, Menara Utara,\r\nBangunan Sultan Idris Shah,\r\n40000 Shah Alam\r\nSelangor",
                'latlng' => null,
                'tel' => '03-55143400',
                'fax' => null,
                'email' => '',
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 4,
                'created_at' => '2014-03-31 02:51:12',
                'updated_at' => '2023-05-23 11:29:43',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 67,
                'name' => 'Bahagian Pengurusan Sumber Manusia',
                'short_name' => 'BPSM',
                'parent_id' => 22,
                'lft' => 40,
                'rgt' => 41,
                'depth' => 1,
                'district_id' => null,
                'address' => 'Tingkat 3, Bangunan SSAAS\r\n40503 Shah Alam, Selangor',
                'latlng' => null,
                'tel' => '03-55447964',
                'fax' => null,
                'email' => '',
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 1,
                'created_at' => '2015-01-08 08:13:12',
                'updated_at' => '2016-05-09 09:23:57',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 68,
                'name' => 'Seksyen Makro & Penswastaan, UPEN',
                'short_name' => 'UPEN Makro',
                'parent_id' => 22,
                'lft' => 42,
                'rgt' => 43,
                'depth' => 1,
                'district_id' => null,
                'address' => "Tingkat 16, Bangunan Sultan Salahuddin Abdul Aziz Shah, \r\n40000 Shah Alam, Selangor",
                'latlng' => null,
                'tel' => '03-55447114',
                'fax' => null,
                'email' => '',
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 1,
                'created_at' => '2016-05-09 09:21:24',
                'updated_at' => '2019-04-16 04:58:32',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 69,
                'name' => 'Pejabat Dewan Negeri Selangor',
                'short_name' => 'DNS',
                'parent_id' => null,
                'lft' => 157,
                'rgt' => 158,
                'depth' => 0,
                'district_id' => null,
                'address' => "Pejabat Dewan Negeri Selangor\r\n, Tingkat 1, Wisma Dewan Negeri Selangor\r\n 40680 Shah Alam, Selangor Darul Ehsan. ",
                'latlng' => null,
                'tel' => '03-55447615',
                'fax' => null,
                'email' => '',
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 1,
                'created_at' => '2016-06-10 02:54:43',
                'updated_at' => '2023-05-23 11:29:43',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 70,
                'name' => 'Bahagian Korporat',
                'short_name' => 'Korporat',
                'parent_id' => 22,
                'lft' => 159,
                'rgt' => 160,
                'depth' => 1,
                'district_id' => null,
                'address' => 'Tingkat Bawah, Bangunan SSAAS, 40503 Shah Alam',
                'latlng' => null,
                'tel' => '03-55447040',
                'fax' => null,
                'email' => '',
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 1,
                'created_at' => '2016-12-23 08:31:51',
                'updated_at' => '2023-05-23 11:29:43',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 71,
                'name' => 'Jabatan Mufti Negeri Selangor',
                'short_name' => 'MUFTI',
                'parent_id' => 22,
                'lft' => 56,
                'rgt' => 57,
                'depth' => 1,
                'district_id' => null,
                'address' => "Tingkat 7 & 8, Menara Utara, Bangunan Sultan Idris Shah,\r\n40000 Shah Alam, Selangor Darul Ehsan.",
                'latlng' => null,
                'tel' => '03-55143738',
                'fax' => null,
                'email' => 'mail@muftiselangor.gov.my',
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 1,
                'created_at' => '2017-03-24 08:47:01',
                'updated_at' => '2023-05-23 11:24:31',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 72,
                'name' => 'Suruhanjaya Perkhidmatan Awam Negeri Selangor',
                'short_name' => 'SPN',
                'parent_id' => null,
                'lft' => 161,
                'rgt' => 162,
                'depth' => 0,
                'district_id' => null,
                'address' => "Tingkat 2, Bangunan Darul Ehsan, No.3 Jalan Indah, Seksyen 14,\r\n40646 Shah Alam, Selangor",
                'latlng' => null,
                'tel' => '03-55111611',
                'fax' => null,
                'email' => 'spnadmin@selangor.gov.my',
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 4,
                'created_at' => '2017-04-14 08:39:28',
                'updated_at' => '2023-05-23 11:29:43',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 73,
                'name' => 'Jabatan Kebajikan Masyarakat Negeri Selangor',
                'short_name' => 'JKM Sel',
                'parent_id' => 22,
                'lft' => 58,
                'rgt' => 59,
                'depth' => 1,
                'district_id' => null,
                'address' => "Tingkat 2, Bangunan Darul Ehsan, No. 3, Jalan Indah, Seksyen 14, 40000 Shah Alam, Selangor",
                'latlng' => null,
                'tel' => '03-55101400',
                'fax' => null,
                'email' => null,
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 1,
                'created_at' => '2018-02-07 07:02:14',
                'updated_at' => '2023-05-23 11:25:06',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 74,
                'name' => 'Jabatan Bomba Dan Penyelamat Negeri Selangor',
                'short_name' => 'Bomba Sel',
                'parent_id' => null,
                'lft' => 163,
                'rgt' => 164,
                'depth' => 0,
                'district_id' => null,
                'address' => "No. 3, Persiaran Tebar Layar Bukit Jelutong, Seksyen U8, 40150 Shah Alam, Selangor",
                'latlng' => null,
                'tel' => '03-78464444',
                'fax' => null,
                'email' => 'korporat@bomba.gov.my',
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 4,
                'created_at' => '2019-01-17 08:01:34',
                'updated_at' => '2023-05-23 11:29:43',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 77,
                'name' => 'Jabatan Pendakwaan Syariah Selangor',
                'short_name' => 'JPNS',
                'parent_id' => 22,
                'lft' => 60,
                'rgt' => 61,
                'depth' => 1,
                'district_id' => null,
                'address' => "Tingkat 5, Menara Selatan\r\nBangunan Sultan Idris Shah,\r\nNo 2., Persiaran Masjid, Bukit SUK, Seksyen 5,\r\n40676 Shah Alam, Selangor Darul Ehsan",
                'latlng' => null,
                'tel' => '03-55143491',
                'fax' => null,
                'email' => null,
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 1,
                'created_at' => '2019-02-13 02:55:12',
                'updated_at' => '2023-05-23 11:25:44',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 78,
                'name' => 'Unit Korporat Multimedia',
                'short_name' => 'KM',
                'parent_id' => 48,
                'lft' => 45,
                'rgt' => 46,
                'depth' => 2,
                'district_id' => null,
                'address' => 'Bahagian Pengurusan Maklumat, Pejabat Setiausaha Kerajaan Negeri Selangor, Tingkat 2, Bangunan Sultan Salahuddin Abdul Aziz Shah',
                'latlng' => null,
                'tel' => '',
                'fax' => null,
                'email' => '',
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 1,
                'created_at' => '2019-04-16 05:02:49',
                'updated_at' => '2019-08-22 08:15:23',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 79,
                'name' => 'Yayasan Selangor',
                'short_name' => 'Yayasan Sel',
                'parent_id' => null,
                'lft' => 165,
                'rgt' => 166,
                'depth' => 0,
                'district_id' => null,
                'address' => "Bahagian Perolehan,\r\nTingkat 14, Menara Yayasan Selangor,\r\nNo18A. Persiaran Barat,                           \r\n46000 Petaling Jaya, Selangor \r\n\r\n",
                'latlng' => null,
                'tel' => '03-76691226 / 192 / 225',
                'fax' => null,
                'email' => 'perolehan@yselangor.com',
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 4,
                'created_at' => '2019-08-02 02:05:30',
                'updated_at' => '2023-05-23 11:29:43',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 80,
                'name' => 'Pejabat DYMM Sultan Selangor',
                'short_name' => 'Pej DYMM',
                'parent_id' => 22,
                'lft' => 62,
                'rgt' => 63,
                'depth' => 1,
                'district_id' => null,
                'address' => 'Istana Alam Shah, 41500 Klang, Selangor',
                'latlng' => null,
                'tel' => '01-33713411',
                'fax' => null,
                'email' => 'ruzaini.raub@selangor.gov.my',
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 1,
                'created_at' => '2019-10-11 03:36:16',
                'updated_at' => '2023-05-23 11:26:20',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
            [
                'id' => 81,
                'name' => 'Lembaga Perumahan Dan Hartanah Negeri Selangor',
                'short_name' => 'LPHS',
                'parent_id' => null,
                'lft' => 167,
                'rgt' => 168,
                'depth' => 0,
                'district_id' => null,
                'address' => "Lembaga Perumahan Dan Hartanah Negeri Selangor (LPHS)\r\nTingkat 5, Podium Utara, \r\nBangunan Sultan Salahuddin Abdul Aziz Shah, \r\n40503, Shah Alam, Selangor",
                'latlng' => null,
                'tel' => '03-55447169',
                'fax' => null,
                'email' => null,
                'confirmation_agency' => 0,
                'user_id' => null,
                'type_id' => 4,
                'created_at' => '2020-04-28 10:01:23',
                'updated_at' => '2023-05-23 11:29:43',
                'sort_no' => null,
                'ori_type_id' => null,
            ],
        ];

        DB::table('organization_units')->insert($rows);

        $this->command->info('✔ organization_units table seeded successfully.');
    }
}
