<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::table('tender_vendors', function (Blueprint $table) {
            // Vendor elimination tracking (generic, reusable across all process stages)
            // 0 = Active, 1 = Eliminated
            $table->tinyInteger('cancel_fg')->default(0)->after('submitted')->index();
            // The status_process_id at which the vendor was eliminated (e.g. 8 = Penilaian Pembuka)
            $table->integer('eliminated_process_id')->nullable()->after('cancel_fg');
            // Human-readable combined reason string (auto-generated by the system)
            $table->text('eliminated_reason')->nullable()->after('eliminated_process_id');
            $table->timestamp('eliminated_at')->nullable()->after('eliminated_reason');

            // Jawatankuasa Pembuka rumusan fields
            // 1 = Bumiputera, 0 = Bukan Bumiputera, null = belum diisi
            $table->tinyInteger('is_bumiputera')->nullable()->after('eliminated_at');
            // Confirmed offer price from Jawatankuasa Pembuka rumusan
            $table->decimal('harga_tawaran', 30, 2)->nullable()->after('is_bumiputera');
        });
    }

    public function down(): void
    {
        Schema::table('tender_vendors', function (Blueprint $table) {
            $table->dropColumn([
                'cancel_fg',
                'eliminated_process_id',
                'eliminated_reason',
                'eliminated_at',
                'is_bumiputera',
                'harga_tawaran',
            ]);
        });
    }
};
